#! /usr/bin/python

import sys

def usage():
    print "texmake [filename]"

def main(args):
    filename = "INSERT_TEX_FILENAME" if (args == []) else args[0]
    print """
TEXFILE = {}

$(TEXFILE).pdf: $(TEXFILE).tex
\tknuth build $<

.PHONY: clean
clean:
\tknuth clean

view: $(TEXFILE).pdf
\tif command -v evince; then evince $<; \\
\telif command -v open; then open $<; \\
\telse echo "ERROR: unable to open pdf. Try installing evince"; fi
""".format(filename)

if __name__ == "__main__":
    main(sys.argv[1:])
